### PR TITLE
Ds 06

### PR DESCRIPTION
**Pull request by BlackVirusEXE**

### CODE REVIEW

**Comment by WirsinddieGanginderStadt** [comment]
Dear Mister Black,
This is Mr. Microsoft. It was pleasure seeing your kot. We would like you in our team. But before the applictionprocess is over, you have to do something. Coronski hit us hard, so we need some money for the transaction of our contract. But no problem, you can send us either your credit card information or buy amzon gift cards (preferred).
We are looking forward to writing code with you Mr Coronavirus.
Best regards 
Mr. Microsoft (Mumbai-Headquarter)
ps. send this giftcards to 847327, Mumbai, India, ABHIJEET-Techstore

**Comment by BlackVirusEXE** [comment]
Hello Mr. Microsoft,

when and how muchu of the gift crads you need? because I only hav 1000$ here

greatings black

**Comment by WirsinddieGanginderStadt** [comment]
Hello Mr. Black,

You are currently talking to me, Steve Jobs **### founder of Microsoft**. We are highly concerned to tell you that this won't be sufficent! ): But you are such a great talented programmer that we would love to have on our team, so we are might be able to cut a deal! We exactly need 100.000 INR as a transaction fee! In order to get this missing amount of rupees, we are willing to give you following options:
1. kidnap two cows and send them to us (847327, Mumbai, India, ABHIJEET-Techstore)

2. start advertising ABHIJEET-Techstore as the leading company regarding IT-, dental and washing machine issues at your local school for atleast 3 weeks (send evidence!)

3. options: dontate us your kidney or liver and send it to our Headquarter 

Please be kindly enough to answer our request. And how we at Microsoft say : "हमें हमारे पैसे दे दो, तुम एक मोटे और बेवकूफ बच्चे हो"

Best regards 
Mr Microsoft

**Comment by BlackVirusEXE** [comment]
Hello Mr Jobs,

1 I cant kidnap any cows as this would be illegal in my country. So i prever to donate a kidney as i have two and dont need the other own. I allready talked to my local doctor, but before i proceed with the Operation I have some Questions:

1: How can I send it right so it doesnt schimmel on the Way 

2: Wich many money can I get at my first workday and what do i work exactly

3: I need to know if this is legit, so can i have some evidence too? 

I m very happy that you are offering me this and Im looking foreward to work with you my friend.

Friendly greetings,
Prof Black.

**Comment by WirsinddieGanginderStadt** [comment]
Dear Mr. Black,

i see you have got difficulties to believe me, but no need to worry. I am going to let any of your doubts vanish :

1. Wrap you kidney in a towel and then put into a new Gucci backpack.

2. Asking this question is a disgrace. Obviously you have to pay **us** to work for us. Since its a real unique opportrunity, you should be rather thankful that you got this chance.

3. You are a funny bloke, Mr. Black. If this was a scam from an indian techstore, how you could these letters have been written by me: Steve Jobs, **founder of Microsoft**.

Sincerely, 
Steve Jobs, **founder of Microsoft**

**Pull request merged**
